### ISSUE TITLE
Styling isn't added

### ISSUE THREAD

**Issue by cdedreuille** [claus/react-dat-gui#48] opened 2020-02-10 15:00 UTC
Hi,

I've tried to play with this controller but no styles were applied to it. In your codesandox the package is from "@tim-soft/react-dat-gui" ut in your doc it's "react-dat-gui". If I use the one you shared in your example, I have some sort of styles applied, quite broken ut at least I can see something.

Am I missing something here?

**Comment by rohan-deshpande** [comment] 2020-02-11 09:13
Closing, duplicate of #43

**Closed by rohan-deshpande** 2020-02-11 09:13 UTC
